edit of the action for testing

diff --git a/.github/workflows/testAction.yml b/.github/workflows/testAction.yml
--- a/.github/workflows/testAction.yml
+++ b/.github/workflows/testAction.yml
@@ -1,9 +1,5 @@
 name: Python test action
 on: 
-  push:
-    branches:
-      - main
-  
   pull_request:
     branches:
       - main 
@@ -25,6 +21,11 @@ jobs:
         shell: cmd
         run: python -m unittest -v test.test_validator
 
+      - name: Force fail for testing
+        run: |
+          echo "This step will fail"
+          exit 1
+
   ubuntu-test:
     runs-on: ubuntu-latest
     steps:
@@ -38,3 +39,8 @@ jobs:
       
       - name: Test Validator
         run: python -m unittest -v test.test_validator  
+
+      - name: Force fail for testing
+        run: |
+          echo "This step will fail"
+          exit 1
